### ISSUE TITLE
YW-Logo als 512x512px Größe

### ISSUE THREAD

**Issue by Art4** [youthweb/promo#1]
Wir benötigen das blaue YW-Logo als 512x512px. Im Moment gibt es das nur als 400x400px.

https://github.com/youthweb/promo/blob/master/Logos/yw-logo_400x400_blau.png

**Comment by Art4** [comment]
ping @olikos

**Comment by real-napster** [comment]
Ist als 1:1 Format hinterlegt... Kleiner machen könnt ihr selber :)
