### ISSUE TITLE
YW-Schriftzug in der Größe 1024 x 500px

### ISSUE THREAD

**Issue by Art4** [youthweb/promo#2]
Für den Google Play Store wird der YW-Schriftzug in der Größe 1024 x 500 px benötigt. Also im Grunde dieses Bild, nur in besserer Auflösung:

![https://youthweb.net/assets/default/img/youthweb_logo.jpg](https://youthweb.net/assets/default/img/youthweb_logo.jpg)

ping @olikos

**Comment by real-napster** [comment]
Gibt es in der Art wie oben im Bild nicht mehr... Bitte dann auf die Datei "yw-Schriftmarke-blau..." zugreifen

**Comment by Art4** [comment]
Danke Ben :tada: 

Besser wird es wohl sein, yw-Schriftmarke-weiß zu verwenden und den Hintergrund auf blau (#1c60a1) zu setzen.
